require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AutoresController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Autor. As you add validations to Autor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AutoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all autores as @autores" do
      autor = Autor.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:autores)).to eq([autor])
    end
  end

  describe "GET show" do
    it "assigns the requested autor as @autor" do
      autor = Autor.create! valid_attributes
      get :show, {:id => autor.to_param}, valid_session
      expect(assigns(:autor)).to eq(autor)
    end
  end

  describe "GET new" do
    it "assigns a new autor as @autor" do
      get :new, {}, valid_session
      expect(assigns(:autor)).to be_a_new(Autor)
    end
  end

  describe "GET edit" do
    it "assigns the requested autor as @autor" do
      autor = Autor.create! valid_attributes
      get :edit, {:id => autor.to_param}, valid_session
      expect(assigns(:autor)).to eq(autor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Autor" do
        expect {
          post :create, {:autor => valid_attributes}, valid_session
        }.to change(Autor, :count).by(1)
      end

      it "assigns a newly created autor as @autor" do
        post :create, {:autor => valid_attributes}, valid_session
        expect(assigns(:autor)).to be_a(Autor)
        expect(assigns(:autor)).to be_persisted
      end

      it "redirects to the created autor" do
        post :create, {:autor => valid_attributes}, valid_session
        expect(response).to redirect_to(Autor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved autor as @autor" do
        post :create, {:autor => invalid_attributes}, valid_session
        expect(assigns(:autor)).to be_a_new(Autor)
      end

      it "re-renders the 'new' template" do
        post :create, {:autor => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested autor" do
        autor = Autor.create! valid_attributes
        put :update, {:id => autor.to_param, :autor => new_attributes}, valid_session
        autor.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested autor as @autor" do
        autor = Autor.create! valid_attributes
        put :update, {:id => autor.to_param, :autor => valid_attributes}, valid_session
        expect(assigns(:autor)).to eq(autor)
      end

      it "redirects to the autor" do
        autor = Autor.create! valid_attributes
        put :update, {:id => autor.to_param, :autor => valid_attributes}, valid_session
        expect(response).to redirect_to(autor)
      end
    end

    describe "with invalid params" do
      it "assigns the autor as @autor" do
        autor = Autor.create! valid_attributes
        put :update, {:id => autor.to_param, :autor => invalid_attributes}, valid_session
        expect(assigns(:autor)).to eq(autor)
      end

      it "re-renders the 'edit' template" do
        autor = Autor.create! valid_attributes
        put :update, {:id => autor.to_param, :autor => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested autor" do
      autor = Autor.create! valid_attributes
      expect {
        delete :destroy, {:id => autor.to_param}, valid_session
      }.to change(Autor, :count).by(-1)
    end

    it "redirects to the autores list" do
      autor = Autor.create! valid_attributes
      delete :destroy, {:id => autor.to_param}, valid_session
      expect(response).to redirect_to(autores_url)
    end
  end

end
